<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="IMG\Animations\camera.json" />
    <None Remove="IMG\new\add.png" />
    <None Remove="IMG\new\beijing.png" />
    <None Remove="IMG\new\bofang.png" />
    <None Remove="IMG\new\close.png" />
    <None Remove="IMG\new\cy.png" />
    <None Remove="IMG\new\david.png" />
    <None Remove="IMG\new\dayin.png" />
    <None Remove="IMG\new\diannao.png" />
    <None Remove="IMG\new\dp.png" />
    <None Remove="IMG\new\faild.png" />
    <None Remove="IMG\new\fanhui.png" />
    <None Remove="IMG\new\gj.png" />
    <None Remove="IMG\new\jg.png" />
    <None Remove="IMG\new\min.png" />
    <None Remove="IMG\new\password_login.png" />
    <None Remove="IMG\new\qjfd.png" />
    <None Remove="IMG\new\serach.png" />
    <None Remove="IMG\new\set22.png" />
    <None Remove="IMG\new\successe2.png" />
    <None Remove="IMG\new\sxt.png" />
    <None Remove="IMG\new\tixing.png" />
    <None Remove="IMG\new\user_login.png" />
    <None Remove="IMG\new\yinsi.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="IMG\Animations\camera.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Content Include="IMG\new\add.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="IMG\new\bofang.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="IMG\new\beijing.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="IMG\new\close.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="IMG\new\cy.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="IMG\new\david.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="IMG\new\dayin.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="IMG\new\diannao.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="IMG\new\dp.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="IMG\new\faild.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="IMG\new\fanhui.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="IMG\new\gj.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="IMG\new\jg.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="IMG\new\min.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="IMG\new\password_login.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="IMG\new\qjfd.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="IMG\new\serach.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="IMG\new\successe2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="IMG\new\sxt.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="IMG\new\tixing.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="IMG\new\user_login.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="IMG\new\set22.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="IMG\new\yinsi.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="MonitoringStationData\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HandyControl" Version="3.5.1" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.4" />
    <PackageReference Include="LottieSharp" Version="2.4.3" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.10" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

</Project>
